app/notifications/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, TextAreaField
from wtforms.validators import DataRequired, AnyOf

class NotificationFormCreate(FlaskForm):
    legend = StringField('New Notification')
    label = StringField('Subject', validators=[DataRequired()])
    message = TextAreaField('Message', validators=[DataRequired()])
    sms_alert = SelectField('Notify via', choices=[('0', 'e-mail (default)'), ('1', 'text message (if set)')],
                            validators=[DataRequired(), AnyOf(['0', '1'])])
    display_image = SelectField('Display image', choices=[('0', 'hidden image (default)'), ('1', 'custom image (if set)')],
                            validators=[DataRequired(), AnyOf(['0', '1'])])
    submit = SubmitField('Create Notification')

class NotificationFormUpdate(FlaskForm):
    legend = StringField('Update Notification')
    label = StringField('Subject', validators=[DataRequired()])
    message = TextAreaField('Message', validators=[DataRequired()])
    sms_alert = SelectField('Notify via', choices=[('0', 'e-mail (default)'), ('1', 'text message (if set)')], validators=[DataRequired(), AnyOf(['0','1'])])
    submit = SubmitField('Update Notification')

app/main/routes.py
from flask import Blueprint,current_app
from flask import render_template, request
from app.models import Notification, Data
from flask_login import login_user, current_user, logout_user, login_required

main = Blueprint('main', __name__)

# #todo disable cache
# @current_app.after_request
# def add_header(r):
#     """
#     Add headers to both force latest IE rendering engine or Chrome Frame,
#     and also to cache the rendered page for 10 minutes.
#     """
#     r.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
#     r.headers["Pragma"] = "no-cache"
#     r.headers["Expires"] = "0"
#     r.headers['Cache-Control'] = 'public, max-age=0'
#     return r


@main.route("/")
@main.route("/home")
#todo modify home to not use current user data
def home():
    notifications = []
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        notifications = Notification.query.filter_by(user_id=current_user.id).order_by(Notification.created_at.desc()).paginate(page=page,per_page=4)

    return render_template('home.html', title='Home', notifications=notifications)

@main.route("/statistics")
def statistics():
    data = Data.query.get(1)
    return render_template('statistics.html',title='Statistics', data=data)

@main.route("/about")
def about():
    return render_template('about.html', title='About')

#todo howto
@main.route("/howto")
def howto():
    return render_template('howto.html', title='How To')

#todo contact
@main.route("/contact")
def contact():
    return render_template('contact.html', title='Contact')

app/notifications/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort, send_from_directory, send_file
from app.notifications.forms import NotificationFormCreate, NotificationFormUpdate
from app import db
from app.models import Notification, User, Data
from flask_login import current_user, login_required
from datetime import datetime
import os, secrets
from app.notifications.utils import send_alert_email, sms_alert_to_bool, display_image_to_bool, destination,use_image


notifications = Blueprint('notifications', __name__)

STATIC_FILE_PATH = os.path.join('static','profile')

@notifications.route("/home/notification/new", methods=['GET', 'POST'])
@login_required
def new_notification():
    form = NotificationFormCreate()
    if form.validate_on_submit():
        token = secrets.token_urlsafe(4)
        notification = Notification(label=form.label.data, message=form.message.data, sms_alert=sms_alert_to_bool(form.sms_alert.data, current_user),superior=current_user, token=token, display_image=display_image_to_bool(form.display_image.data, current_user))
        db.session.add(notification)
        data = Data.query.get(1)
        data.total_notifications = data.total_notifications + 1
        db.session.commit()
        flash('Notification successfully created.', 'success')

        return redirect(url_for('notifications.notification', notification_id=notification.id))#return redirect(url_for('main.home'))
    return render_template('create_notification.html', title='Create Notification', form=form)




@notifications.route("/home/notification/<int:notification_id>")
@login_required
def notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if notification.superior == current_user:
        return render_template('notification.html', title=notification.label, notification=notification)

    return redirect(url_for('main.home'))



@notifications.route("/home/notification/<int:notification_id>/update", methods=['GET', 'POST'])
@login_required
def update_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if notification.superior != current_user:
        return redirect(url_for('main.home'))
    form = NotificationFormUpdate()
    if form.validate_on_submit():
        notification.label = form.label.data
        notification.message = form.message.data
        notification.sms_alert = sms_alert_to_bool(form.sms_alert.data, current_user)
        # notification.display_image = display_image_to_bool(form.display_image.data, current_user)
        db.session.commit()
        flash('Your Notification has been updated.', 'success')
        return redirect(url_for('notifications.notification', notification_id=notification.id))
    elif request.method == 'GET':
        form.label.data = notification.label
        form.message.data = notification.message
        form.sms_alert.data = notification.sms_alert
        # form.display_image.data = notification.display_image
    return render_template('create_notification.html', title='Update Notification',
                           form=form, legend='Update Notification')


@notifications.route("/home/notification/<int:notification_id>/delete", methods=['POST'])
@login_required
def delete_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if notification.superior != current_user:
        return redirect(url_for('main.home'))
    db.session.delete(notification)
    db.session.commit()
    flash('Your Notification has been deleted.', 'success')
    return redirect(url_for('main.home'))

@notifications.after_request
def add_header(r):
    """
    Add headers to both force latest IE rendering engine or Chrome Frame,
    and also to cache the rendered page for 10 minutes.
    """
    r.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    r.headers["Pragma"] = "no-cache"
    r.headers["Expires"] = "0"
    r.headers['Cache-Control'] = 'public, max-age=0'
    return r

@notifications.route("/<int:notification_id>/<string:token>")
def alert(notification_id, token):
    notification = Notification.query.get(notification_id)
    if notification:
        if notification.token == token:
            user = User.query.get(notification.user_id)
            if notification.alarm == True:
                notification.alert_count = notification.alert_count + 1
                notification.last_alert = datetime.utcnow()
                data = Data.query.get(1)
                data.total_alerts = data.total_alerts + 1
                data.last_alert = notification.last_alert
                db.session.commit()
                note_dest = destination(user, notification)
                send_alert_email(note_dest, notification.label, notification.message)
                return send_from_directory(STATIC_FILE_PATH, use_image(user,notification))
            else:# notification.alarm == False
                notification.alarm = True
                db.session.commit()
                return send_from_directory(STATIC_FILE_PATH, use_image(user,notification))

        return send_from_directory(STATIC_FILE_PATH, 'Default.png')

app/users/routes.py
import secrets
from flask import render_template, url_for, flash, redirect, request, abort,Blueprint
from app.users.forms import RegistrationForm, LoginForm,UpdateAccountForm, RequestResetForm, ResetPasswordForm, PhoneSMSForm, PhoneSMSTokenForm, UpdateEmailForm, UpdatePasswordForm
from app import db, bcrypt
from app.models import User, Notification, Data
from flask_login import login_user, current_user, logout_user, login_required
from datetime import datetime
from app.users.utils import save_image, send_reset_email, sms_provider_list, send_phone_sms

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(email=form.email.data, password=hashed_password)
        db.session.add(user)
        data = Data.query.get(1)
        data.total_users = data.total_users + 1
        db.session.commit()
        flash(f'Account created for {form.email.data}!', 'success') #bootstrap class
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)




@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            user.last_signin = datetime.utcnow()
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.after_request
def add_header(r):
    """
    Add headers to both force latest IE rendering engine or Chrome Frame,
    and also to cache the rendered page for 10 minutes.
    """
    r.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    r.headers["Pragma"] = "no-cache"
    r.headers["Expires"] = "0"
    r.headers['Cache-Control'] = 'public, max-age=0'
    return r

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.image.data:
            if bcrypt.check_password_hash(current_user.password, form.password.data):
                image_file = save_image(form.image.data, form.image_size.data, current_user.email)
                current_user.image_file = image_file
                db.session.commit()
                flash('Image successfully updated.', 'success')
            else:
                flash('Invalid Password.', 'warning')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.email.data = current_user.email
        if current_user.activation_code is None:
            form.phone_sms.data = current_user.phone_sms
    image_file = url_for('static', filename='profile/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

@users.route("/update_email", methods=['GET', 'POST'])
@login_required
def update_email():
    form = UpdateEmailForm()
    if form.validate_on_submit():
        if bcrypt.check_password_hash(current_user.password, form.password.data):
            current_user.email = form.email.data
            db.session.commit()
            flash(f'Your email has been updated!', 'success')
        else:
            flash('Invalid Password.', 'warning')
            return redirect(url_for('users.update_email'))

        return redirect(url_for('users.account'))
    return render_template('update_email.html', title='Update Email', form=form)

@users.route("/update_password", methods=['GET', 'POST'])
@login_required
def update_password():
    form = UpdatePasswordForm()
    if form.validate_on_submit():
        if bcrypt.check_password_hash(current_user.password, form.current_password.data):
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            current_user.password = hashed_password
            db.session.commit()
            flash(f'Your password has been updated!', 'success') #bootstrap class
        else:
            flash('Current password invalid.', 'warning')
            return redirect(url_for('users.update_password'))

        return redirect(url_for('users.account'))
    return render_template('update_password.html', title='Update Password', form=form)


@users.route("/admin/user/<string:email>")
@login_required
def admin_user_notifications(email):
    if current_user.id is 1:
        page = request.args.get('page',1,type=int)
        user = User.query.filter_by(email=email).first_or_404()
        notifications = Notification.query.filter_by(superior=user).order_by(Notification.created_at.desc()).paginate(page=page,per_page=4)
        return render_template('admin_user_notifications.html', notifications=notifications,user=user)
    else:
        return render_template('404.html'), 404

#todo fix
@users.route("/admin/users")
@login_required
def admin_users():
    if current_user.id is 1:
        users = User.query.order_by(User.created_at.desc()).all()
        return render_template('admin_users.html',users=users)
    else:
        return render_template('404.html'), 404


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if User is None:
        flash('Token is invalid or expired.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated! You are now able to log in', 'success') #bootstrap class
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


#==============================
@users.route("/phone_sms", methods=['GET', 'POST'])
@login_required
def phone_sms_setup():
    form = PhoneSMSForm()
    if form.validate_on_submit():
        current_user.phone_sms = form.number.data + sms_provider_list(form.carrier.data)
        current_user.activation_code = secrets.token_urlsafe(5)
        db.session.commit()
        send_phone_sms(current_user)
        flash('An activation code has been sent to your phone.', 'info')
        return redirect(url_for('users.phone_sms_activate'))
    return render_template('phone_sms.html', title='Phone Text Notification', form=form)

@users.route("/phone_sms/activate", methods=['GET', 'POST'])
@login_required
def phone_sms_activate():
    if current_user.activation_code is None:
        return redirect(url_for('users.phone_sms_setup'))
    form = PhoneSMSTokenForm()
    if form.validate_on_submit():
        if current_user.activation_code != form.number.data:
            flash('The activation code was invalid or mistyped. Please try again.', 'warning')
            return redirect(url_for('users.phone_sms_activate'))

        current_user.activation_code = None
        db.session.commit()
        flash(f'Your phone has been successfully added!', 'success') #bootstrap class
        return redirect(url_for('users.account'))
    return render_template('phone_sms.html', title='Activate Text Notification', form=form)

app/templates/about.html
{% extends "layout.html" %}
{% block content %}

      <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
        <h2>About</h2>
        </div>
          <p class="article-content">
              It all started with my brother showing me how using a service allowed him to receive email notifications once the recipient viewed his email. I thought about how it could have been implemented and decided to create it. Notified.tk tries to provide a subtle way of receiving notifications while minimizing the amount of information you need to provide to use the service. Since this is a free service, access is currently limited to friends, family, and associates. I hope Notified.tk helps ease your mind when an important email is sent. Enjoy!
          </p>
      </div>
    </article>
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
        <h2>How it works</h2>
        </div>
          <p class="article-content">
              When you create a notification, a unique html code is generated that looks like so...
              <br><input type="text" class="form-control" value="<img src='https://notified.tk/1/fYYw8Q'>">
              <a href="{{ url_for('main.howto') }}">You then embed the above html code into an email before sending.</a>
              <br>Once the recipient opens the email, their browser will request to load the unique image from notified.tk
              <br>notified.tk will return the image and secretly notify you.
              <br>The recipient will either see no image (a transparent image) or your custom image.
          </p>
      </div>
    </article>
{% endblock content %}

app/templates/admin_user_notifications.html
{% extends "layout.html" %}
{% block scripts %}
    <script type = "text/javascript" src="{{ url_for('static', filename='js/utils.js') }}"></script>
{% endblock scripts %}
{% block content %}
    <h3 class="mb-3 text-muted">{{ user.email }} ({{ user.id }})</h3>
    {% if notifications %}
        {% for notification in notifications.items %}
            <article class="media content-section">
              <div class="media-body">
                <div class="article-metadata">
                  <small class="text-muted"><span class="utc_date">{{ notification.created_at}}</span></small>
                </div>
                  <h3><a class="article-title" href="{{ url_for('notifications.notification', notification_id=notification.id) }}">{{ notification.label }}</a></h3>
                <p class="article-content">{{ notification.message }}</p>
                  <p class="article-content"><small class="text-muted">Views: {{ notification.alert_count }}
                      Last Viewed: <span class="utc_date">{{ notification.last_alert }}</span></small></p>
              </div>
            </article>
        {% endfor %}
        {% for page_num in notifications.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if page_num %}
            {% if notifications.page == page_num %}
              <a class="btn btn-info mb-4" href="{{ url_for('users.admin_user_notifications', email=user.email, page=page_num) }}">{{ page_num }}</a>
            {% else %}
              <a class="btn btn-outline-info mb-4" href="{{ url_for('users.admin_user_notifications', email=user.email, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
          {% else %}
            ...
          {% endif %}
        {% endfor %}
    {% else %}
        <h2>This User has no Notifications.</h2>
    {% endif %}
{% endblock content %}

app/templates/admin_users.html
{% extends "layout.html" %}
{% block scripts %}
    <script type = "text/javascript" src="{{ url_for('static', filename='js/utils.js') }}"></script>
{% endblock scripts %}
{% block content %}
    <h3 class="mb-3 text-muted">All Users</h3>
    {% if users %}
        {% for user in users.items %}
            <article class="media content-section">
              <div class="media-body">
                <div class="article-metadata">
                  <small class="text-muted"><span class="utc_date">{{ user.created_at}}</span></small>
                </div>
                  <h2><a class="article-title" href="{{ url_for('users.admin_user_notifications', email=user.email) }}">{{ user.email }}</a></h2>
                <p class="article-content">Text: {{ user.phone_sms }}</p>
                  <p class="article-content"><small class="text-muted">Last Signin: <span class="utc_date">{{ user.last_signin }}</span></small></p>
              </div>
            </article>
        {% endfor %}

    {% else %}
        <h2>There are no users...</h2>
    {% endif %}
{% endblock content %}

app/templates/contact.html
{% extends "layout.html" %}

{% block scripts %}
    <script type = "text/javascript" src="{{ url_for('static', filename='js/utils.js') }}"></script>
{% endblock scripts %}

{% block content %}

      <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
        <h2>Contact</h2>
        </div>
          <p class="article-content">
            <h3 align="center" class="text-muted">Emmanuel</h3>
            <h4 align="center"><i><span id="e9uefu9a">Notified.tk</span></i></h4>
          </p>
      </div>
    </article>
{% endblock content %}

app/templates/home.html
{% extends "layout.html" %}
{% block scripts %}
    <script type = "text/javascript" src="{{ url_for('static', filename='js/utils.js') }}"></script>
{% endblock scripts %}

{% block content %}
        {% if notifications %}
                <h2>Notifications</h2>
            {% if notifications.items == [] %}
              <article class="media content-section">
              <div class="media-body">
                <div class="article-metadata">
                <h4>No Notifications Set</h4>
                </div>
                  <p class="article-content"><a href="{{ url_for('notifications.new_notification') }}">Create notification?</a></p>
              </div>
            </article>
            {%  endif %}
        {% for notification in notifications.items %}
            <article class="media content-section">
              <div class="media-body">
                <div class="article-metadata">
                  <small class="text-muted"><span class="utc_date">{{ notification.created_at}}</span></small>
                </div>
                  <h3><a class="article-title" href="{{ url_for('notifications.notification', notification_id=notification.id) }}">{{ notification.label }}</a></h3>
                <p class="article-content">{{ notification.message }}</p>
                  <p class="article-content"><small class="text-muted">Views: {{ notification.alert_count }}
                      Last Viewed: <span class="utc_date">{{ notification.last_alert }}</span></small><a class="btn btn-info btn-sm m-1 float-right" href="{{ url_for('notifications.notification', notification_id=notification.id) }}">Inspect</a></p>
              </div>
            </article>
        {% endfor %}
        {% for page_num in notifications.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if page_num %}
            {% if notifications.page == page_num %}
              <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
              <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
          {% else %}
            ...
          {% endif %}
        {% endfor %}
    {% else %}
            <br><br><br>
            <h5 class="text-muted">Ever wondered if they viewed your email?</h5>
            <h1 align="center"><i>Notified.tk</i></h1>
        {% endif %}
{% endblock content %}

app/templates/howto.html
{% extends "layout.html" %}

{% block scripts %}
    <script type = "text/javascript" src="{{ url_for('static', filename='js/utils.js') }}"></script>
{% endblock scripts %}

{% block content %}

      <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
        <h2>How-to</h2>
        </div>
          <p class="article-content">
        <div class="alert alert-warning" role="alert">
          <strong>Foreword</strong><br>I strongly encourage you to test this first with an email to yourself to see how it all works together and to test if your email provider does not sanitize foreign html on outbound emails. It is important to note that if a provider sanitizes outbound emails, it does not mean they sanitize inbound emails, so it will work the other way around. Sending an email from gmail will not work but receiving an email to gmail will work.
        </div>
          <div class="alert alert-warning" role="alert">
          This list is incomplete. If you discover that notified.tk works or does not work with another email provider, feel free to send an email to <i><span id="e9uefu9a">Notified.tk</span></i> and i'll update this list accordingly.
        </div>
          <div class="alert alert-success" role="alert">
              <strong>Works from...</strong>
              <br>- Protonmail
            </div>

          <div class="alert alert-danger" role="alert">
          <strong>Does not work from...</strong>
              <br>- Gmail
        </div>
          <h4 align="center"><a href="https://www.useloom.com/share/df5661ed9f0b4f4dabefe595fcc44357" target="_blank">How-To Video, click here</a></h4>
          </p>
      </div>
    </article>
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Notified.tk - {{ title }}</title>
    {% else %}
        <title>Notified.tk</title>
    {% endif %}

    {% block scripts %}{% endblock %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/"><i>Notified.tk</i></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>

            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('notifications.new_notification') }}">New Notification</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>

        <div class="col-md-4">
          <div class="content-section">

            <p class='text-muted'>
              <ul class="list-group">
              <li class="list-group-item list-group-item-light"><a class="sidebar-link" href="{{ url_for('main.about') }}">About</a></li>
              <li class="list-group-item list-group-item-light"><a class="sidebar-link" href="{{ url_for('main.howto') }}">How-to</a></li>
              <li class="list-group-item list-group-item-light"><a class="sidebar-link" href="{{ url_for('main.statistics') }}">Statistics</a></li>
              <li class="list-group-item list-group-item-light"><a class="sidebar-link" href="{{ url_for('main.contact') }}">Contact</a></li>
              </ul>
            </p>
          </div>
        </div>

      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/templates/statistics.html
{% extends "layout.html" %}
{% block scripts %}
    <script type = "text/javascript" src="{{ url_for('static', filename='js/utils.js') }}"></script>
{% endblock scripts %}

{% block content %}
            <article class="media content-section">
              <div class="media-body">
                <div class="article-metadata">
                    <h3>Application Statistics</h3>
                </div>
                <p class="article-content">Total Users: {{ data.total_users }}</p>
                  <p class="article-content">Notifications created: {{ data.total_notifications }}</p>
                  <p class="article-content">Alerts sent: {{ data.total_alerts }}</p>
                  <p class="article-content">Last Alert: <span class="utc_date">{{ data.last_alert }}</span></p>
              </div>
            </article>

{% endblock content %}